<?php

/**
 * Implementation of hook_webform_submission_insert()
 */
function athletescan_webform_submission_insert($node, $submission) {
  // $node->nid will be the node id of your webfom
  if ($node->nid == 742) {
    $submitted_data = $submission->data;
    $user_name = $submitted_data[142][0]; 
    $password = $submitted_data[141][0];
    $email = $submitted_data[18][0];
    $user_data = array();
    // check if mail exists
    $user = user_load_by_mail($email);
    if (!empty($user->uid)) {
      $account = user_load($user->uid);

    }

    // Need to populate following data for registering the user.
    $user_data['init'] = $email;
    $user_data['mail'] = $email;
    $user_data['name'] = $user_name;
    $user_data['pass'] = $password;
    $user_data['status'] = 1;
    if (empty($user->uid)) {
      $acuser = user_save(NULL, $user_data);
    }
    else {
      $acuser = user_save($account, $user_data);
    }
    $acuser->roles = $acuser->roles + array(8 => 'official members');
    user_save($acuser);
  }
}
